### ISSUE TITLE
It doesn't look well in terminal

### ISSUE THREAD

**Issue by tonivj5** [MarcusCemes/responsive-image-builder#8]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
It doesn't show well
![image](https://user-images.githubusercontent.com/7110786/81600745-64150f00-93ca-11ea-88e2-33dc7fa517e2.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I'm using `zsh` in KDE with `Konsole`, I have tried with `bash` too. It looks weird, as if it doesn't repaint well.

PS: Really cool project :+1:

**Comment by MarcusCemes** [comment]
Thanks 🍻. I have a new major update coming out in the near future, which among other features, will take advantage of a better terminal library (instead of one of my own projects!). I'll keep this open until the release.

**Comment by tonivj5** [comment]
Thanks for your fast reply! :clap:

**Comment by MarcusCemes** [comment]
It's taken a while, but here it is. This should no longer be a problem in the new version, however, there are many breaking API changes.

The project has also been renamed to Image Processing Pipeline, mostly due to an already occupied npm scope, so you'll need to replace it with the `@ipp/cli` package. There's some new documentation to help you get started.
